import type { Board } from "../boards/interfaces";

export const boards: Board[] = [
    {
        id: '1',
        title: 'Default',
        type: 'todo',
        progressCurrent: 13,
        progressTotal: 20,
        pinned: true,
        locked: true,
        project_id: '1',
        section_id: '1',
    },
    {
        id: '2',
        title: 'Karabiner',
        type: 'todo',
        progressCurrent: 25,
        progressTotal: 30,
        pinned: true,
        locked: true,
        active: true,
        project_id: '1',
        section_id: '1',
    },
    {
        id: '3',
        title: 'Dictionary',
        type: 'todo',
        progressCurrent: 15,
        progressTotal: 50,
        locked: true,
        project_id: '1',
        section_id: '1',
    },
    {
        id: '4',
        title: 'Paradise Falls',
        type: 'todo',
        progressCurrent: 5,
        progressTotal: 10,
        project_id: '1',
        section_id: '1',
    },
    {
        id: '5',
        title: 'Group Link',
        type: 'todo',
        progressCurrent: 42,
        progressTotal: 73,
        project_id: '1',
        section_id: '1',
    },
    {
        id: '6',
        title: 'Artificer',
        type: 'todo',
        progressCurrent: 0,
        progressTotal: 22,
        locked: true,
        project_id: '1',
        section_id: '1',
    },
    {
        id: '7',
        title: 'Open Dash',
        type: 'document',
        countDocs: 34,
        countNotes: 70,
        project_id: '1',
        section_id: '1',
    },
    {
        id: '8',
        title: 'Darmanitan',
        type: 'document',
        countDocs: 110,
        countNotes: 56,
        project_id: '1',
        section_id: '1',
    },
];
