import type { RawNode } from '../nodes/interfaces';

export const nodes: RawNode[] = [
    // root - 1st card
    {
        id: '0',
        title: 'ROOT',
        parent_id: '-1',
        project_id: '1',
        order: 10,
    },
    {
        id: '1',
        title: 'Node In-Progress',
        parent_id: '0',
        project_id: '1',
        order: 100,
    },
    {
        id: '01',
        title: 'Node In-Progress - 01',
        parent_id: '2',
        project_id: '1',
        order: 10,
    },
    {
        id: '011',
        title: 'Node 011',
        parent_id: '01',
        project_id: '1',
        order: 10,
    },
    {
        id: '0101',
        title: 'Lorem ipsum dolor sit amet',
        parent_id: '0',
        project_id: '1',
        order: 15,
    },
    {
        id: '2',
        title: 'Consectetur adipiscing elit',
        parent_id: '0',
        project_id: '1',
        order: 20,
    },
    {
        id: '22',
        title: 'Node 22',
        parent_id: '2',
        project_id: '1',
        order: 20,
    },
    {
        id: '222',
        title: 'Node 222',
        parent_id: '2',
        project_id: '1',
        order: 30,
    },
    {
        id: '2222',
        title: 'Node 2222',
        parent_id: '2',
        project_id: '1',
        order: 40,
    },
    {
        id: '2222.1',
        title: 'Node 2222.1',
        parent_id: '2222',
        project_id: '1',
        order: 10,
    },
    {
        id: '22222',
        title: 'Node 22222',
        parent_id: '2',
        project_id: '1',
        order: 50,
    },
    {
        id: '3',
        title: 'Node 3',
        parent_id: '2',
        project_id: '1',
        order: 60,
    },
    {
        id: '33',
        title: 'Node 33',
        parent_id: '3',
        project_id: '1',
        order: 10,
    },
    {
        id: '333',
        title: 'Node 333',
        parent_id: '3',
        project_id: '1',
        order: 20,
    },
    {
        id: '333.1',
        title: 'Node 333.1',
        parent_id: '333',
        project_id: '1',
        order: 10,
    },
    {
        id: '3333',
        title: 'Node 3333',
        parent_id: '333',
        project_id: '1',
        order: 20,
    },
    {
        id: '4',
        title: 'Node 4',
        parent_id: '2',
        project_id: '1',
        order: 70,
    },
    {
        id: '5',
        title: 'Node 5',
        parent_id: '0',
        project_id: '1',
        order: 30,
    },
    {
        id: '6',
        title: 'Node 6',
        parent_id: '5',
        project_id: '1',
        order: 10,
    },
    {
        id: '7',
        title: 'Node 7',
        parent_id: '6',
        project_id: '1',
        order: 10,
    },
    {
        id: '8',
        title: 'Node 8',
        parent_id: '5',
        project_id: '1',
        order: 20,
    },
    // 2nd card root
    {
        id: '100',
        title: 'ROOT',
        parent_id: 'a',
        project_id: '1',
        order: 10,
    },
    {
        id: '101',
        title: 'Node Alpha',
        parent_id: '100',
        project_id: '1',
        order: 10,
    },
    {
        id: '102',
        title: 'Node Beta',
        parent_id: '100',
        project_id: '1',
        order: 20,
    },
    {
        id: '103',
        title: 'Node Gamma',
        parent_id: '100',
        project_id: '1',
        order: 30,
    },
    {
        id: '104',
        title: 'Node Delta',
        parent_id: '101',
        project_id: '1',
        order: 10,
    },
    {
        id: '105',
        title: 'Node Epsilon',
        parent_id: '102',
        project_id: '1',
        order: 10,
    },
    {
        id: '106',
        title: 'Node Zeta',
        parent_id: '103',
        project_id: '1',
        order: 10,
    },
    {
        id: '107',
        title: 'Node Eta',
        parent_id: '104',
        project_id: '1',
        order: 10,
    },
    {
        id: '108',
        title: 'Node Theta',
        parent_id: '105',
        project_id: '1',
        order: 10,
    },
    {
        id: '109',
        title: 'Node Iota',
        parent_id: '106',
        project_id: '1',
        order: 10,
    },
    {
        id: '110',
        title: 'Node Kappa',
        parent_id: '104',
        project_id: '1',
        order: 20,
    },
    {
        id: '111',
        title: 'Node Lambda',
        parent_id: '105',
        project_id: '1',
        order: 20,
    },
    {
        id: '112',
        title: 'Node Mu',
        parent_id: '106',
        project_id: '1',
        order: 20,
    },
    {
        id: '113',
        title: 'Node Nu',
        parent_id: '107',
        project_id: '1',
        order: 10,
    },
    {
        id: '114',
        title: 'Node Xi',
        parent_id: '108',
        project_id: '1',
        order: 10,
    },
    {
        id: '115',
        title: 'Node Omicron',
        parent_id: '109',
        project_id: '1',
        order: 10,
    },
    {
        id: '116',
        title: 'Node Pi',
        parent_id: '110',
        project_id: '1',
        order: 10,
    },
    {
        id: '117',
        title: 'Node Rho',
        parent_id: '111',
        project_id: '1',
        order: 10,
    },
    {
        id: '118',
        title: 'Node Sigma',
        parent_id: '112',
        project_id: '1',
        order: 10,
    },
    {
        id: '119',
        title: 'Node Tau',
        parent_id: '113',
        project_id: '1',
        order: 10,
    },
    // 3rd card root
    {
        id: '200',
        title: 'ROOT',
        parent_id: 'b',
        project_id: '1',
        order: 10,
    },
    {
        id: '201',
        title: 'Node One',
        parent_id: '200',
        project_id: '1',
        order: 10,
    },
    {
        id: '202',
        title: 'Node Two',
        parent_id: '200',
        project_id: '1',
        order: 20,
    },
    {
        id: '203',
        title: 'Node Three',
        parent_id: '200',
        project_id: '1',
        order: 30,
    },
    {
        id: '204',
        title: 'Node Four',
        parent_id: '201',
        project_id: '1',
        order: 10,
    },
    {
        id: '205',
        title: 'Node Five',
        parent_id: '201',
        project_id: '1',
        order: 20,
    },
    {
        id: '206',
        title: 'Node Six',
        parent_id: '202',
        project_id: '1',
        order: 10,
    },
    {
        id: '207',
        title: 'Node Seven',
        parent_id: '202',
        project_id: '1',
        order: 20,
    },
    {
        id: '208',
        title: 'Node Eight',
        parent_id: '203',
        project_id: '1',
        order: 10,
    },
    {
        id: '209',
        title: 'Node Nine',
        parent_id: '203',
        project_id: '1',
        order: 20,
    },
    {
        id: '210',
        title: 'Node Ten',
        parent_id: '204',
        project_id: '1',
        order: 10,
    },
    {
        id: '211',
        title: 'Node Eleven',
        parent_id: '205',
        project_id: '1',
        order: 10,
    },
    {
        id: '212',
        title: 'Node Twelve',
        parent_id: '206',
        project_id: '1',
        order: 10,
    },
    {
        id: '213',
        title: 'Node Thirteen',
        parent_id: '207',
        project_id: '1',
        order: 10,
    },
    {
        id: '214',
        title: 'Node Fourteen',
        parent_id: '208',
        project_id: '1',
        order: 10,
    },
    {
        id: '215',
        title: 'Node Fifteen',
        parent_id: '209',
        project_id: '1',
        order: 10,
    },
    {
        id: '216',
        title: 'Node Sixteen',
        parent_id: '210',
        project_id: '1',
        order: 10,
    },
    {
        id: '217',
        title: 'Node Seventeen',
        parent_id: '211',
        project_id: '1',
        order: 10,
    },
    {
        id: '218',
        title: 'Node Eighteen',
        parent_id: '212',
        project_id: '1',
        order: 10,
    },
    {
        id: '219',
        title: 'Node Nineteen',
        parent_id: '213',
        project_id: '1',
        order: 10,
    },
];
