import type { RawNodeState } from "../nodes/interfaces";

export const nodeStates: RawNodeState[] = [
    {
        id: '0',
        primary: true,
        expanded: true,
        complete: false,
        node_id: '0',
        project_id: '1',
    },
    {
        id: '1',
        primary: true,
        expanded: true,
        complete: false,
        node_id: '1',
        project_id: '1',
    },
    {
        id: '01',
        primary: false,
        expanded: true,
        complete: true,
        node_id: '01',
        project_id: '1',
    },
    {
        id: '011',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '011',
        project_id: '1',
    },
    {
        id: '2',
        primary: false,
        expanded: true,
        complete: false,
        node_id: '2',
        project_id: '1',
    },
    {
        id: '22',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '22',
        project_id: '1',
    },
    {
        id: '222',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '222',
        project_id: '1',
    },
    {
        id: '2222',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '2222',
        project_id: '1',
    },
    {
        id: '2222.1',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '2222.1',
        project_id: '1',
    },
    {
        id: '22222',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '22222',
        project_id: '1',
    },
    {
        id: '3',
        primary: false,
        expanded: true,
        complete: false,
        node_id: '3',
        project_id: '1',
    },
    {
        id: '33',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '33',
        project_id: '1',
    },
    {
        id: '333',
        primary: false,
        expanded: true,
        complete: false,
        node_id: '333',
        project_id: '1',
    },
    {
        id: '333.1',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '333.1',
        project_id: '1',
    },
    {
        id: '3333',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '3333',
        project_id: '1',
    },
    {
        id: '4',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '4',
        project_id: '1',
    },
    {
        id: '5',
        primary: true,
        expanded: true,
        complete: false,
        node_id: '5',
        project_id: '1',
    },
    {
        id: '6',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '6',
        project_id: '1',
    },
    {
        id: '7',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '7',
        project_id: '1',
    },
    {
        id: '8',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '8',
        project_id: '1',
    },
    // 2nd card
    {
        id: '100',
        primary: true,
        expanded: true,
        complete: false,
        node_id: '100',
        project_id: '1',
    },
    {
        id: '101',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '101',
        project_id: '1',
    },
    {
        id: '102',
        primary: false,
        expanded: true,
        complete: false,
        node_id: '102',
        project_id: '1',
    },
    {
        id: '103',
        primary: false,
        expanded: true,
        complete: true,
        node_id: '103',
        project_id: '1',
    },
    {
        id: '104',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '104',
        project_id: '1',
    },
    {
        id: '105',
        primary: false,
        expanded: true,
        complete: true,
        node_id: '105',
        project_id: '1',
    },
    {
        id: '106',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '106',
        project_id: '1',
    },
    {
        id: '107',
        primary: false,
        expanded: true,
        complete: false,
        node_id: '107',
        project_id: '1',
    },
    {
        id: '108',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '108',
        project_id: '1',
    },
    {
        id: '109',
        primary: false,
        expanded: true,
        complete: true,
        node_id: '109',
        project_id: '1',
    },
    {
        id: '110',
        primary: false,
        expanded: true,
        complete: false,
        node_id: '110',
        project_id: '1',
    },
    {
        id: '111',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '111',
        project_id: '1',
    },
    {
        id: '112',
        primary: false,
        expanded: true,
        complete: false,
        node_id: '112',
        project_id: '1',
    },
    {
        id: '113',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '113',
        project_id: '1',
    },
    {
        id: '114',
        primary: false,
        expanded: true,
        complete: true,
        node_id: '114',
        project_id: '1',
    },
    {
        id: '115',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '115',
        project_id: '1',
    },
    {
        id: '116',
        primary: false,
        expanded: true,
        complete: false,
        node_id: '116',
        project_id: '1',
    },
    {
        id: '117',
        primary: false,
        expanded: false,
        complete: false,
        node_id: '117',
        project_id: '1',
    },
    {
        id: '118',
        primary: false,
        expanded: true,
        complete: true,
        node_id: '118',
        project_id: '1',
    },
    {
        id: '119',
        primary: false,
        expanded: false,
        complete: true,
        node_id: '119',
        project_id: '1',
    },
];
